apiVersion: v1
kind: Pod
metadata:
  name: node-port-status
  namespace: vmware-nodes-project
spec:
  containers:
    - name: node-port-status
      image: 265765232051.dkr.ecr.us-east-1.amazonaws.com/node_port_status:latest
      env:
      - name: AWS_BUCKET
        value: "vmware-node-status-project-arnold"
      - name: IGNORE_LIST
        value: "22 35 80"
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: aws-credentials
            key: AWS_SECRET_ACCESS_KEY
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: aws-credentials
            key: AWS_ACCESS_KEY_ID
  serviceAccountName: get-node-info
  restartPolicy: Always



  AWS_ACCESS_KEY_ID