#kubectl create secret generic aws-credentials --from-env-file=env-secrets.env
apiVersion: v1
kind: Namespace
metadata:
   name: nodes-project
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: get-node-info
  namespace: nodes-project
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: get-node-status
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-status-getter
roleRef:
  kind: ClusterRole
  name: get-node-status
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: get-node-info
    namespace: nodes-project
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: nodes-project
type: Opaque
data:
#SECRETS, USE SEALEDSECRETS TO HIDE THIS VARIABLES
  AWS_ACCESS_KEY_ID: 
  AWS_SECRET_ACCESS_KEY: 
